# Generated by Django 4.2.19 on 2025-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
