# Generated by Django 4.2.19 on 2025-03-25 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsettings',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='setting_key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('BOOKING', 'Booking Report'), ('BUS', 'Bus Report'), ('USER', 'User Report'), ('REVENUE', 'Revenue Report')], max_length=20),
        ),
    ]
